config/routes.rb
Rails.application.routes.draw do
 

  root 'home#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  get '/logout', to: 'sessions#destroy', as: :logout
  get "/test", to: "sessions#create"

  scope '/api', :defaults => {:format => :json} do
    get "/home", to: "home#homePage"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
  	  user = find_or_initialize_by(uid: auth[:uid])
      user.uid = auth[:uid]
      user.nickname = auth[:info][:nickname]
      user.avatar_url = auth[:extra][:raw_info][:avatarfull]
      user.save!
      user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find_by(uid: session[:user_id]) if session[:user_id]
  end

helper_method :current_user


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homePage
  	render json: '{"newPlayers":"30","totalPlayers":"20","gamesPlayed":"3152","todayWon":"12.15$","lastWinners":[{"name":"test","money":"0.15","game":"R","date":"Сегодня"},{"name":"test","money":"0.15","game":"R","date":"Сегодня"},{"name":"test","money":"0.15","game":"R","date":"Сегодня"},{"name":"test","money":"0.15","game":"R","date":"Сегодня"},{"name":"test","money":"0.15","game":"R","date":"Сегодня"}]}
'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create

  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
session[:user_id] = user[:uid]
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
<div class="col-sm-12 col-md-8">


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1" ></li>

        </ol>   
        <!-- Wrapper for carousel items -->
        <div class="carousel-inner">
            <div class="item active">
           <div id="statsContainer">

          <div class="row2 fcstat clearfix">
			                <div class="col col-sm-3"><label>Новых игроков</label> <b>30</b></div>
    			<div class="col col-sm-3"><label>Всего игроков</label> <b>20</b></div>
    			<div class="col col-sm-3"><label>Игр сыграно</label> <b>24</b></div>
    			<div class="col col-sm-3"><label>Сегодня выйграно</label> <b>5.12</b></div>
            		</div>

           </div>
            </div>

               <div class="item">
     <img src="http://placehold.it/450x202">
            </div>
         
        </div>
        <!-- Carousel controls -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>



<div class="box nlist" style="margin-bottom: 0px;">
								                                    <div class="n_item">
    									<div class="row">
    										<div class="col-sm-4">
    										<div class="news_image">
    											<a href="/dota-2/news/474"><img src="http://game-tournaments.com/media/news/pic-20151102-512x221-729904239.jpeg"></a>
    											</div>
    										</div>
    										<div class="col-sm-8">
    											<h2><a href="/dota-2/news/474" title="Alliance забирают путевку на WCA">Alliance забирают путевку на WCA</a></h2>
    											<div class="news-desc">Отрытые квалификация на World Cyber Arena 2015 для европейского региона подошли к концу. В финальном противостоянии bo3 сошлись Team Empire и Alliance, совсем недавно пережившие не самые лучшие времена. </div>
    											<time class="label label-default" style="opacity:.5"><i class="fa fa-fw fa-clock-o"></i> 2 ноября 2015</time>
    										</div>
    									</div>
    								</div>
                                                                    <div class="n_item">
    									<div class="row">
    										<div class="col-sm-4">
    											<div class="news_image">
    											<a href="/dota-2/news/474"><img src="http://game-tournaments.com/media/news/pic-20151102-512x221-729904239.jpeg"></a>
    											</div>
    										</div>
    										<div class="col-sm-8">
    											<h2><a href="/dota-2/news/473" title="Team Secret забрали трофей  Nanyang ">Team Secret забрали трофей  Nanyang </a></h2>
    											<div class="news-desc">Отгремел последний матч Nanyang Dota 2 Championships. Финалисты показали отменную игру, однако сильнее в очередной раз оказались Team Secret. </div>
    											<time class="label label-default" style="opacity:.5"><i class="fa fa-fw fa-clock-o"></i> 2 ноября 2015</time>
    										</div>
    									</div>
    								</div>
                                                                    <div class="n_item">
    									<div class="row">
    										<div class="col-sm-4">
    											<div class="news_image">
    											<a href="/dota-2/news/474"><img src="http://game-tournaments.com/media/news/pic-20151102-512x221-729904239.jpeg"></a>
    											</div>
    										</div>
    										<div class="col-sm-8">
    											<h2><a href="/dota-2/news/472" title="Virtus.Pro получили прямой инвайт на DotaPit">Virtus.Pro получили прямой инвайт на DotaPit</a></h2>
    											<div class="news-desc">Dota Pit объявил список первых участников 4 сезона турнира. Помимо этого был анонсирован регламент соревнования и его призовой фонд. </div>
    											<time class="label label-default" style="opacity:.5"><i class="fa fa-fw fa-clock-o"></i> 1 ноября 2015</time>
    										</div>
    									</div>

    								</div>
    								  <div class="n_item">
    									<div class="row">
    										<div class="col-sm-4">
    											<div class="news_image">
    											<a href="/dota-2/news/474"><img src="http://game-tournaments.com/media/news/pic-20151102-512x221-729904239.jpeg"></a>
    											</div>
    										</div>
    										<div class="col-sm-8">
    											<h2><a href="/dota-2/news/472" title="Virtus.Pro получили прямой инвайт на DotaPit">Virtus.Pro получили прямой инвайт на DotaPit</a></h2>
    											<div class="news-desc">Dota Pit объявил список первых участников 4 сезона турнира. Помимо этого был анонсирован регламент соревнования и его призовой фонд. </div>
    											<time class="label label-default" style="opacity:.5"><i class="fa fa-fw fa-clock-o"></i> 1 ноября 2015</time>
    										</div>
    									</div>
    									
    								</div>
                                                                    
                                				            </div>

</div>
<div class="col-sm-12 col-md-4">
	<div class="box">
    <h3>Последние победители</h3>
    <table class="table table-striped table-condensed">
        <tbody>
            <tr>
                <th>Игрок</th>
                <th class="text-center" width="32px"><i class="fa fa-usd odtip" data-toggle="tooltip" title="Выигрыш"></i></th>
                <th class="text-center" width="32px"><i class="fa fa-gamepad odtip" data-toggle="tooltip" title="Игра"></i></th>
                <th class="text-center" width="67px"><i class="fa fa-fw fa-clock-o odtip" data-toggle="tooltip" title="Время"></i></th>
            </tr>
                            <tr>
                    <td><a href="javascript:;">IWilldominate</a></td>
                    <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;">IronBets</a></td>
                 <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;" onclick="wms_forecaster(5602,582)">piecemeal</a></td>
                   <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;" onclick="wms_forecaster(5156,582)">Live от Uralmass</a></td>
                   <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;" onclick="wms_forecaster(7131,582)">KoAN</a></td>
                   <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                    </tbody>
    </table>
</div>

	<div class="box">
    <h3>Топ выигрышей</h3>
    <table class="table table-striped table-condensed">
        <tbody>
            <tr>
                <th>Игрок</th>
                <th class="text-center" width="32px"><i class="fa fa-usd odtip" data-toggle="tooltip" title="Выигрыш"></i></th>
                <th class="text-center" width="32px"><i class="fa fa-gamepad odtip" data-toggle="tooltip" title="Игра"></i></th>
                <th class="text-center" width="67px"><i class="fa fa-fw fa-clock-o odtip" data-toggle="tooltip" title="Время"></i></th>
            </tr>
                            <tr>
                    <td><a href="javascript:;">IWilldominate</a></td>
                    <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;">IronBets</a></td>
                 <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;" onclick="wms_forecaster(5602,582)">piecemeal</a></td>
                   <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;" onclick="wms_forecaster(5156,582)">Live от Uralmass</a></td>
                   <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                            <tr>
                    <td><a href="javascript:;" onclick="wms_forecaster(7131,582)">KoAN</a></td>
                   <td class="text-center vcenter">0.05</td>
                    <td class="text-center vcenter">R</td>
                    <td class="text-center vcenter">сегодня</td>
                </tr>
                    </tbody>
    </table>
</div>




</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	
<div class="row">
			<div class="col-sm-3">
				<a href="/" class="f_logo"><img src="/images/logo.png" alt="Dota2City.net" width="100px"></a>
				<copy>© 2015</copy>
			</div>
			<div class="col-sm-9">
			  	<div class="f_soc pull-right">
					<a target="_blank" href="https://vk.com/club86056273"><i class="fa fa-fw fa-vk"></i></a>
                    <a target="_blank" href="https://twitter.com/Dota2City?ref_src=twsrc%5Etfw"><i class="fa fa-fw fa-twitter"></i></a>
                    <a target="_blank" href="https://www.facebook.com/Dota2City/?fref=ts"><i class="fa fa-fw fa-facebook"></i></a>
                     <a target="_blank" href="http://steamcommunity.com/groups/dota2city"><i class="fa fa-fw fa-steam"></i></a>

				</div>
				<ul class="f_menu">
					<li><a href="/about">О проекте</a></li>
					<li><a href="/rules">Правила</a></li>
					<li><a href="/ads">Реклама</a></li>
					<li><a href="/partner">Партнеры</a></li>
				</ul>
			 </div>

		</div>

</footer>

app/views/layouts/_leftbar.html.erb
<div id="leftbar-wrapper">
<div id="logo">
<%= image_tag("logo.png", :alt => "logo") %>
</div>
<div class="nav-container">

  <ul class="nav">
    <li class="active">
      <a href="#" ui-sref="home">
        <i class="fa fa-home"></i>
        <span class="text">Главная</span>
      </a>
    </li>
     <li class="">
      <a href="#" ui-sref="test">
        <i class="fa fa-sign-in"></i>
        <span class="text">Ввод</span>
      </a>
    </li>
     <li class="">
      <a href="#">
        <i class="fa fa-sign-out"></i>
        <span class="text">Вывод</span>
      </a>
    </li>
        <li class="">
      <a href="#">
        <i class="fa fa-gamepad"></i>
        <span class="text">Играть</span>
      </a>
    </li>
    <li class="">
      <a href="#">
        <i class="fa fa-info-circle"></i>
        <span class="text">FAQ</span>
      </a>
    </li>

  </ul>

</div>
</div>

app/views/layouts/_rightbar.html.erb
<div id="rightbar-wrapper">

 <% if current_user %>
<div id="user_info">
<%= image_tag current_user.avatar_url, alt: 'Avatar', class: 'img-circle' %>

<span id="user_settings" class="user_buttons"><a href="#" title="Профиль"><i class="fa fa-cogs"></i></a></span>
<span id="user_signout" class="user_buttons"><a href="<%= logout_path %>" title="Выход"><i class="fa fa-sign-out"></i></a></span>
<div id="user_login" class="overflow"><%= current_user.nickname %></div>
<div class="overflow">Баланс: <span id="user_money">0.000</span>$</div>
<div class="overflow">Бонус: <span id="user_bonus">0.000</span>$</div>
</div>

 <% else %>

<div id="login_form">
Авторизируйся через свой Steam аккаунт!
<a href="/auth/steam"><img src="/images/steam.png" alt="steam"></a>
</div>
<% end %>





<div id="chat">
	<div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>
  	<div class="chat_msg"><time class="label label-default time_label"><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Ololowka:</span>
  
    <div class="chat_user_msg">что за обнова ребят?  </div>
  

  </div>

  	<div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Mid or feed:</span>
  
    <div class="chat_user_msg">меняю башер на ам на щит иммортал на свена  </div>
  

  </div>
  <div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>
  <div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>
  <div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>
  <div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>
  <div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>
   <div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>
   <div class="chat_msg"><time class="label label-default time_label" ><i class="fa fa-fw fa-clock-o"></i> 22 октября 2015</time><span class="chat_user_name overflow">Gabby:</span>
  
    <div class="chat_user_msg">Куплю вещи из доты или кs go . Пишем в skype ololodablkill оплата - qiwi. Кидалы не пишите </div>
  

  </div>

</div>
<div class="input-group">
      <input type="text" class="form-control" placeholder="Сообщение" style="border-radius: 0px;">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button" style="border-radius: 0px;"><i class="fa fa-envelope"></i></button>
      </span>
    </div><!-- /input-group -->

</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
<base href="/">
  <title>Dota2City.net</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body ng-app="mainApp">
<div id="wrapper">

<%= render 'layouts/leftbar' %>
<%= render 'layouts/rightbar' %>
<div class="well well-sm content" ui-view>



</div>

<%= render 'layouts/footer' %>
</div>
</body>



  <%= javascript_include_tag 'application' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
<script type="text/javascript">



//$('[data-toggle="tooltip"]').tooltip(); 






</script>
  
</html>